assert(engine_state().agent and not engine_visible())
run_restart() engine_step(30)
assert(player.y>0.32 and player.y<0.5)
engine_snapshot('replays/shots/m1-entrance.png')
agent_walk_to(0,8) agent_look_at(0,1,-4) engine_snapshot('replays/shots/m1-lake.png')
lamp_on=true
agent_walk_to(-6,7,2400,creatures[6]) agent_walk_to(-7.7,2,2400,creatures[6]) agent_walk_to(-12,2,2400,creatures[6])
assert(player.y>6 and player.y<6.7,'vantage was not reached by climbing')
agent_look_at(0,0,-2) engine_snapshot('replays/shots/m1-vantage.png')
player.yaw=-math.pi/2 agent_tap('w',120)
assert(player.x> -14 and player.y<6.8,'climbed through the sheer wall')
player_reset() agent_walk_to(0,7) agent_walk_to(0,-3) agent_walk_to(1.3,-3,300) engine_step(35)
assert(player.sinking>0 and player.y<0.4,'deep water did not remove lift')
run_restart()
return 'M1 PASS: hover, authored route, wall ascent, sheer limit, deep-water loss of lift; 3 snapshots'
