---@meta anchor-engine
-- GENERATED by scripts/gen_api.py from engine/src/anchor.c — do not edit.
-- Declares the engine's C bindings for lua-language-server (`anchor check`).
-- Bindings shadowed by framework wrappers are omitted: the wrapper file is the truth.
-- Untyped parameters are typed by name; UNDOCUMENTED bindings are declared variadic.

--- filter 'smooth' or 'rough' (default: global filter_mode); w,h = fixed backing size (default: follows the window)
---@param name string
---@param filter? string
---@param w? integer
---@param h? integer
---@return lightuserdata
function layer_create(name, filter, w, h) end

--- explicitly resize a layer's FBO (color + depth/ stencil attachments). Fixed-size layers keep their fixed-size exemption from the web resize sweep; this is the deliberate resize path for embedded-game surfaces (full-bleed strips track the window width through this).
---@param layer Layer|lightuserdata
---@param w number
---@param h number
function layer_resize(layer, w, h) end

--- draw a texture CENTERED at (cx, cy); color tints (default white), flash whitens (default 0)
---@param layer Layer|lightuserdata
---@param tex lightuserdata|table
---@param cx number
---@param cy number
---@param color? integer
---@param flash? integer
function layer_draw_texture(layer, tex, cx, cy, color, flash) end

--- 'smooth'/'linear' = mipmapped linear (photos), else nearest (pixel art); web: nil while the file is still fetching
---@param path string
---@param filter? string
---@return lightuserdata
function texture_load(path, filter) end

--- texture userdata High-quality CPU resample to (at most) the target size; for crisp downscaling.
---@param path string
---@param target_w any
---@param target_h any
---@return any
function texture_load_fit(path, target_w, target_h) end

--- width, height  (header-only; nil if it can't be read)
---@param path string
---@return any
function image_info(path) end

--- true (once) when async-fetched web images have arrived since the last call. The renderer polls this and re-lays-out the page so newly present images appear. Always false on desktop (no async fetch).
---@return boolean
function images_dirty() end

--- "ready" | "pending" | "failed" Lets the renderer lazy-load page bodies (data/<slug>.lua) the way images lazy-load: "ready"   = the file is in the FS now -> dofile it. "pending" = being fetched over HTTP -> show a loading state, poll images_dirty(), retry. "failed"  = not present / not fetchable. Desktop has no async fetch: "ready" if the file exists on disk, else "failed" (so the renderer's load path stays fully synchronous on desktop).
---@param path string
---@return any
function web_file_status(path) end

--- texture userdata pixel_data_string is a binary string of width*height*4 bytes (RGBA)
---@param width number
---@param height number
---@param pixel_data_string any
---@return any
function texture_create(width, height, pixel_data_string) end

--- free a texture
---@param tex lightuserdata|table
function texture_unload(tex) end

---@param tex lightuserdata|table
---@return integer
function texture_get_width(tex) end

---@param tex lightuserdata|table
---@return integer
function texture_get_height(tex) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function spritesheet_load(...) end

---@param sheet lightuserdata|table
---@return integer
function spritesheet_get_frame_width(sheet) end

---@param sheet lightuserdata|table
---@return integer
function spritesheet_get_frame_height(sheet) end

---@param sheet lightuserdata|table
---@return integer
function spritesheet_get_total_frames(sheet) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function layer_draw_spritesheet_frame(...) end

--- filter is 'smooth' or 'rough'; defaults to global filter_mode.
---@param name string
---@param path string
---@param size number
---@param filter? string
function font_load(name, path, size, filter) end

---@param name string
function font_unload(name) end

--- line height in pixels
---@param name string
---@return number
function font_get_height(name) end

--- baseline distance from the top in pixels
---@param name string
---@return number
function font_get_ascent(name) end

---@param name string
---@param text string
---@return number
function font_get_text_width(name, text) end

---@param name string
---@param codepoint integer
---@return number
function font_get_char_width(name, codepoint) end

--- advance/bearing/size fields for one glyph; errors if the font is unknown
---@param name string
---@param codepoint integer
---@return table
function font_get_glyph_metrics(name, codepoint) end

--- text with its TOP-LEFT at (x, y)
---@param layer Layer|lightuserdata
---@param text string
---@param font_name string
---@param x number
---@param y number
---@param color integer
function layer_draw_text(layer, text, font_name, x, y, color) end

--- Live text-rendering controls (A/B comparison). snap is draw-time; interp/gamma/embolden re-bake the glyph atlases. embolden (optional, pixels) adds real stroke weight.
---@param snap_bool any
---@param interp_int any
---@param gamma_number any
---@param embolden_px? any
function font_render_config(snap_bool, interp_int, gamma_number, embolden_px) end

--- one glyph with rotation and scale
---@param layer Layer|lightuserdata
---@param codepoint integer
---@param font_name string
---@param x number
---@param y number
---@param r? number
---@param sx? number
---@param sy? number
---@param color integer
function layer_draw_glyph(layer, codepoint, font_name, x, y, r, sx, sy, color) end

--- (cx,cy) = glyph CENTER.
---@param layer Layer|lightuserdata
---@param codepoint any
---@param font string
---@param cx number
---@param cy number
---@param r? number
---@param sx? number
---@param sy? number
---@param color integer
function layer_draw_glyph_c(layer, codepoint, font, cx, cy, r, sx, sy, color) end

--- turn glyph capture on (clears the buffer) or off.
---@param on boolean
function engine_glyph_capture(on) end

--- array of {cp, font, x, y, w, h, color} for every glyph drawn since capture was turned on. Positions are the on-screen glyph-bitmap top-left; center = (x+w/2, y+h/2).
---@return any
function engine_glyph_capture_read() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function sound_load(...) end

--- fire-and-forget; bits/sr_div = bitcrush and sample-rate-divide DSP (16/1 = clean); start_sec seeks into the clip
---@param sound lightuserdata|table
---@param volume? number
---@param pitch? number
---@param bits? integer
---@param sr_div? integer
---@param start_sec? number
function sound_play(sound, volume, pitch, bits, sr_div, start_sec) end

--- as sound_play, returning a voice handle for the sound_handle_* controls (-1 = no free voice)
---@param sound lightuserdata|table
---@param volume? number
---@param pitch? number
---@param bits? integer
---@param sr_div? integer
---@param start_sec? number
---@return integer
function sound_play_handle(sound, volume, pitch, bits, sr_div, start_sec) end

---@param handle integer
---@param pitch number
function sound_handle_set_pitch(handle, pitch) end

---@param handle integer
---@param volume number
function sound_handle_set_volume(handle, volume) end

---@param handle integer
function sound_handle_stop(handle) end

---@param handle integer
---@param looping boolean
function sound_handle_set_looping(handle, looping) end

--- retune a playing voice's bitcrush / sample-rate-divide
---@param handle integer
---@param bits integer
---@param sr_div integer
function sound_handle_set_dsp(handle, bits, sr_div) end

--- the path the sound was loaded from ('' for nil)
---@param sound lightuserdata|table
---@return string
function sound_get_path(sound) end

--- every loaded sound as {sound = handle, path = string}
---@return table
function sound_list() end

--- Goes through zip_read_file, the same path sounds and textures use, so it works identically for loose files during development and for packaged builds. Lua's io.open would only handle the former.
---@param path string
---@return string | nil
function file_read_string(path) end

--- write a whole file; false on failure
---@param path string
---@param content string
---@return boolean
function file_write_string(path, content) end

--- master sfx volume 0-1
---@param volume number
function sound_set_volume(volume) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_load(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_unload(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_play(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_pause(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_stop(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_seek(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_set_volume(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_set_speed(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_set_looping(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_set_display_size(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_texture(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_get_size(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_get_duration(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_get_time(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function video_get_state(...) end

--- streamed music; errors if the file cannot be opened
---@param path string
---@return lightuserdata
function music_load(path) end

--- channel default 0
---@param music lightuserdata|table
---@param loop? boolean
---@param channel? integer
function music_play(music, loop, channel) end

--- omit the channel to stop all
---@param channel? integer
function music_stop(channel) end

--- omit the channel for the master music volume
---@param volume number
---@param channel? integer
function music_set_volume(volume, channel) end

---@param channel? integer
---@return boolean
function music_is_playing(channel) end

--- a non-looping track reached its end
---@param channel? integer
---@return boolean
function music_at_end(channel) end

--- seconds
---@param channel? integer
---@return number
function music_get_position(channel) end

--- seconds
---@param channel? integer
---@return number
function music_get_duration(channel) end

---@param channel? integer
---@return number
function music_get_volume(channel) end

--- pitch multiplier on all audio (slow-motion sound)
---@param pitch number
function audio_set_master_pitch(pitch) end

--- pack 0-255 channels into the rgba integer draw calls take (a default 255)
---@param r integer
---@param g integer
---@param b integer
---@param a? integer
---@return integer
function rgba(r, g, b, a) end

--- 'smooth' or 'rough': the default filter for layers created afterwards
---@param mode string
function set_filter_mode(mode) end

--- 'smooth' or 'rough'
---@return string
function get_filter_mode() end

--- reset the fixed-step accumulator (after a long stall, so the loop does not spiral catching up)
function timing_resync() end

--- load and activate a custom sprite/shape draw shader (compiles async on web; get_draw_shader is nil until ready)
---@param path string
function set_draw_shader(path) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function get_draw_shader(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function shader_load_file(...) end

--- compile an effect (post-process) shader from source; errors on failure; headless returns 1
---@param source string
---@return integer
function shader_load_string(source) end

---@param shader integer
function shader_destroy(shader) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function shader_set_float_immediate(...) end

--- set a uniform NOW (and record it for replay) — unlike the queued layer_shader_set_*
---@param shader integer
---@param name string
---@param x number
---@param y number
function shader_set_vec2_immediate(shader, name, x, y) end

--- set a uniform NOW (recorded for replay)
---@param shader integer
---@param name string
---@param x number
---@param y number
---@param z number
---@param w number
function shader_set_vec4_immediate(shader, name, x, y, z, w) end

--- set a uniform NOW (recorded for replay)
---@param shader integer
---@param name string
---@param value integer
function shader_set_int_immediate(shader, name, value) end

--- draw src layer's current color texture into a RECT of dst's FBO (top-left game coords in dst space), scaled to w x h. The viewport variant of layer_draw_from: same screen shader and orientation (proven FBO->FBO path), but the fullscreen quad rasterizes only inside the rect. Rects partially outside dst clip naturally. This is the embedded-game composite: a fixed-size game layer placed into the site's document layer at the element's on-screen rect.
---@param dst lightuserdata|table
---@param src lightuserdata|table
---@param x number
---@param y number
---@param w number
---@param h number
function layer_draw_into(dst, src, x, y, w, h) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_init(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_gravity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_meter_scale(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_enabled(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_register_tag(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_enable_collision(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_disable_collision(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_enable_sensor(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_enable_hit(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_tags_collide(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_create_body(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_destroy_body(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_create_distance_joint(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_destroy_joint(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_joint_is_valid(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_distance_joint_set_length(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_distance_joint_set_spring(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_distance_joint_set_length_range(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_position(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_angle(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_body_count(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_body_is_valid(...) end

---@param body lightuserdata|table
---@param tag string
---@param radius number
---@param opts? table
function physics_add_circle(body, tag, radius, opts) end

---@param body lightuserdata|table
---@param tag string
---@param width number
---@param height number
---@param opts? table
function physics_add_box(body, tag, width, height, opts) end

---@param body lightuserdata|table
---@param tag string
---@param length number
---@param radius number
---@param opts? table
function physics_add_capsule(body, tag, length, radius, opts) end

--- vertices is a flat array: {x1, y1, x2, y2, ...}
---@param body lightuserdata|table
---@param tag string
---@param vertices number[]
---@param opts? table
function physics_add_polygon(body, tag, vertices, opts) end

--- vertices is a flat array: {x1, y1, x2, y2, ...} (at least 4 points) is_loop: true for closed loop, false for open chain Returns chain ID as userdata
---@param body lightuserdata|table
---@param tag string
---@param vertices number[]
---@param is_loop any
function physics_add_chain(body, tag, vertices, is_loop) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_position(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_angle(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_transform(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_velocity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_angular_velocity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_velocity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_angular_velocity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_apply_force(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_apply_force_at(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_apply_impulse(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_apply_impulse_at(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_apply_torque(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_apply_angular_impulse(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_linear_damping(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_angular_damping(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_gravity_scale(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_fixed_rotation(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_bullet(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_user_data(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_user_data(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_set_friction(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_get_friction(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_set_restitution(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_get_restitution(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_is_valid(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_get_body(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_set_density(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_get_density(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_destroy(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_shape_set_filter_group(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_body_type(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_get_mass(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_center_of_mass(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_is_awake(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_set_awake(...) end

--- table of shapes with world-space geometry Returns: {{type="circle", x=..., y=..., radius=...}, {type="polygon", vertices={x1,y1,x2,y2,...}}, ...}
---@param body lightuserdata|table
---@return any
function physics_get_shapes_geometry(body) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics_debug_events(...) end

--- array of {body_a, body_b, shape_a, shape_b, tag_a, tag_b, point_x, point_y, normal_x, normal_y}
---@param tag_a string
---@param tag_b string
---@return any
function physics_get_collision_begin(tag_a, tag_b) end

--- array of {body_a, body_b, shape_a, shape_b, tag_a, tag_b}
---@param tag_a string
---@param tag_b string
---@return any
function physics_get_collision_end(tag_a, tag_b) end

--- array of {body_a, body_b, shape_a, shape_b, tag_a, tag_b, point_x, point_y, normal_x, normal_y, approach_speed}
---@param tag_a string
---@param tag_b string
---@return any
function physics_get_hit(tag_a, tag_b) end

--- array of {sensor_body, visitor_body, sensor_shape, visitor_shape, sensor_tag, visitor_tag}
---@param tag_a string
---@param tag_b string
---@return any
function physics_get_sensor_begin(tag_a, tag_b) end

--- array of {sensor_body, visitor_body, sensor_shape, visitor_shape, sensor_tag, visitor_tag}
---@param tag_a string
---@param tag_b string
---@return any
function physics_get_sensor_end(tag_a, tag_b) end

--- array of bodies
---@param x number
---@param y number
---@param tags string[]
---@return any
function physics_query_point(x, y, tags) end

--- array of bodies
---@param x number
---@param y number
---@param radius number
---@param tags string[]
---@return any
function physics_query_circle(x, y, radius, tags) end

--- array of bodies
---@param x number
---@param y number
---@param w number
---@param h number
---@param tags string[]
---@return any
function physics_query_aabb(x, y, w, h, tags) end

--- array of bodies (rotated box)
---@param x number
---@param y number
---@param w number
---@param h number
---@param angle number
---@param tags string[]
---@return any
function physics_query_box(x, y, w, h, angle, tags) end

--- array of bodies
---@param x1 number
---@param y1 number
---@param x2 number
---@param y2 number
---@param radius number
---@param tags string[]
---@return any
function physics_query_capsule(x1, y1, x2, y2, radius, tags) end

--- array of bodies vertices is a flat array: {x1, y1, x2, y2, ...}
---@param x number
---@param y number
---@param vertices number[]
---@param tags string[]
---@return any
function physics_query_polygon(x, y, vertices, tags) end

--- {body, shape, point_x, point_y, normal_x, normal_y, fraction} or nil Returns the closest hit that matches the tag filter
---@param x1 number
---@param y1 number
---@param x2 number
---@param y2 number
---@param tags string[]
---@return table
function physics_raycast(x1, y1, x2, y2, tags) end

--- array of {body, shape, point_x, point_y, normal_x, normal_y, fraction}
---@param x1 number
---@param y1 number
---@param x2 number
---@param y2 number
---@param tags string[]
---@return any
function physics_raycast_all(x1, y1, x2, y2, tags) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_init(...) end

--- destroy the 3D world and reset all engine-side 3D physics state so a fresh physics3_init starts clean. Used by the site's game host to switch between embedded games (each re-inits its own world). The static-geometry registries (meshes/height fields) are process-lifetime by design and deliberately not freed here.
function physics3_shutdown() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_gravity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_enabled(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_restitution_threshold(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_hit_event_threshold(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_register_tag(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_enable_collision(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_disable_collision(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_enable_sensor(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_enable_hit(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_tags_collide(...) end

--- body userdata
---@param type any
---@param x number
---@param y number
---@param z number
---@return any
function physics3_create_body(type, x, y, z) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_destroy_body(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_body_is_valid(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_body_count(...) end

--- shape
---@param body lightuserdata|table
---@param tag string
---@param radius number
---@param opts? table
---@return any
function physics3_add_sphere(body, tag, radius, opts) end

--- shape A box is a convex hull in Box3D; hull data is cloned into the shape.
---@param body lightuserdata|table
---@param tag string
---@param width number
---@param height number
---@param depth any
---@param opts? table
---@return any
function physics3_add_box(body, tag, width, height, depth, opts) end

--- shape height is the TOTAL height (tip to tip). opts.axis = 'x'|'y'|'z' (default 'y').
---@param body lightuserdata|table
---@param tag string
---@param height number
---@param radius number
---@param opts? table
---@return any
function physics3_add_capsule(body, tag, height, radius, opts) end

--- shape Convex hull approximation (opts.sides, default 12), y-axis aligned.
---@param body lightuserdata|table
---@param tag string
---@param height number
---@param radius number
---@param opts? table
---@return any
function physics3_add_cylinder(body, tag, height, radius, opts) end

--- shape points is a flat array {x1, y1, z1, x2, y2, z2, ...} in body-local meters.
---@param body lightuserdata|table
---@param tag string
---@param points number[]
---@param opts? table
---@return any
function physics3_add_hull(body, tag, points, opts) end

--- shape Static terrain. The height field data is referenced by the shape (not cloned) and registered for process lifetime.
---@param body lightuserdata|table
---@param tag string
---@param rows integer
---@param cols integer
---@param sx number
---@param sy number
---@param sz number
---@param row_freq any
---@param col_freq any
---@return any
function physics3_add_heightfield_wave(body, tag, rows, cols, sx, sy, sz, row_freq, col_freq) end

--- shape Static flat grid mesh (referenced, registered for process lifetime).
---@param body lightuserdata|table
---@param tag string
---@param x_count any
---@param z_count any
---@param cell_width any
---@return any
function physics3_add_grid_mesh(body, tag, x_count, z_count, cell_width) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_position(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_rotation(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_position(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_rotation(...) end

---@param body lightuserdata|table
---@param x number
---@param y number
---@param z number
---@param qx any
---@param qy any
---@param qz any
---@param qw any
function physics3_set_transform(body, x, y, z, qx, qy, qz, qw) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_velocity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_velocity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_angular_velocity(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_angular_velocity(...) end

--- vx, vy, vz Velocity of the WORLD point rigidly attached to the body: v_com + w x r. A force-based vehicle needs this at every contact patch, and computing it in Lua would require the body's center of mass, which only Box3D knows exactly.
---@param body lightuserdata|table
---@param x number
---@param y number
---@param z number
---@return any
function physics3_get_point_velocity(body, x, y, z) end

--- x, y, z The center of mass in BODY-LOCAL coordinates. physics3_get_position returns the body ORIGIN, and the two differ whenever shapes are offset — which is how you give a vehicle a low center of mass.
---@param body lightuserdata|table
---@return any
function physics3_get_local_center(body) end

--- Kinematic drive: sets the velocity that reaches the given transform after dt. A kinematic body moved with set_transform TELEPORTS and pushes nothing; driven this way it carries a real velocity and shoves dynamic bodies properly.
---@param body lightuserdata|table
---@param x number
---@param y number
---@param z number
---@param qx any
---@param qy any
---@param qz any
---@param qw any
---@param dt number
---@param wake? any
function physics3_set_target_transform(body, x, y, z, qx, qy, qz, qw, dt, wake) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_apply_force(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_apply_force_at(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_apply_impulse(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_apply_impulse_at(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_apply_torque(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_apply_angular_impulse(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_linear_damping(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_angular_damping(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_gravity_scale(...) end

--- The 3D replacement for set_fixed_rotation: lock any combination of axes.
---@param body lightuserdata|table
---@param lin_x any
---@param lin_y any
---@param lin_z any
---@param ang_x any
---@param ang_y any
---@param ang_z any
function physics3_set_motion_locks(body, lin_x, lin_y, lin_z, ang_x, ang_y, ang_z) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_bullet(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_user_data(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_user_data(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_body_type(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_get_mass(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_is_awake(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_set_awake(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_set_friction(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_get_friction(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_set_restitution(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_get_restitution(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_set_density(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_get_density(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_is_valid(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_get_body(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_destroy(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_shape_set_filter_group(...) end

--- array of event tables
---@param tag_a string
---@param tag_b string
---@return any
function physics3_get_collision_begin(tag_a, tag_b) end

--- array of event tables
---@param tag_a string
---@param tag_b string
---@return any
function physics3_get_collision_end(tag_a, tag_b) end

--- array of event tables (with approach_speed)
---@param tag_a string
---@param tag_b string
---@return any
function physics3_get_hit(tag_a, tag_b) end

--- array of event tables
---@param sensor_tag any
---@param visitor_tag any
---@return any
function physics3_get_sensor_begin(sensor_tag, visitor_tag) end

--- array of event tables
---@param sensor_tag any
---@param visitor_tag any
---@return any
function physics3_get_sensor_end(sensor_tag, visitor_tag) end

--- array of bodies
---@param x number
---@param y number
---@param z number
---@param tags string[]
---@return any
function physics3_query_point(x, y, z, tags) end

--- array of bodies
---@param x number
---@param y number
---@param z number
---@param radius number
---@param tags string[]
---@return any
function physics3_query_sphere(x, y, z, radius, tags) end

--- array of bodies
---@param min_x any
---@param min_y any
---@param min_z any
---@param max_x any
---@param max_y any
---@param max_z any
---@param tags string[]
---@return any
function physics3_query_aabb(min_x, min_y, min_z, max_x, max_y, max_z, tags) end

--- array of bodies (axis-aligned box)
---@param x number
---@param y number
---@param z number
---@param w number
---@param h number
---@param d number
---@param tags string[]
---@return any
function physics3_query_box(x, y, z, w, h, d, tags) end

--- array of bodies (y-axis capsule)
---@param x number
---@param y number
---@param z number
---@param height number
---@param radius number
---@param tags string[]
---@return any
function physics3_query_capsule(x, y, z, height, radius, tags) end

--- hit table or nil
---@param x1 number
---@param y1 number
---@param z1 any
---@param x2 number
---@param y2 number
---@param z2 any
---@param tags string[]
---@return any
function physics3_raycast(x1, y1, z1, x2, y2, z2, tags) end

--- array of hit tables
---@param x1 number
---@param y1 number
---@param z1 any
---@param x2 number
---@param y2 number
---@param z2 any
---@param tags string[]
---@return any
function physics3_raycast_all(x1, y1, z1, x2, y2, z2, tags) end

--- Spring-drags a body toward a world target (initially the grab point). Rotation is left free, matching classic mouse-joint feel. Default max_force scales with the body's mass so heavy and light bodies feel the same.
---@param body lightuserdata|table
---@param px any
---@param py any
---@param pz any
---@param hertz__damping__max_force? any
function physics3_create_grab_joint(body, px, py, pz, hertz__damping__max_force) end

--- joint Ball-and-socket at world point (ax, ay, az), with optional cone and twist limits and a rotational spring. The spring is the point: set `hertz` and then feed physics3_joint_set_target_rotation() the rotation the ANIMATION wants between the two bodies, and the joint drives the limb back to the pose after something knocks it away. That's a powered ragdoll with no state machine — the recovery is the spring, not a scripted blend. Both local frames are built with identity rotation, so "frame B relative to frame A" is just inverse(rotA)*rotB. A target of identity therefore means "both bodies aligned as they were when the joint was made" — i.e. the rest pose, if you build the joints in it. opts: cone (radians, <=0 disables), twist_lo, twist_hi (radians, equal disables), hertz, damping, collide (default false)
---@param bodyA any
---@param bodyB any
---@param ax number
---@param ay number
---@param az number
---@param opts? table
---@return any
function physics3_create_spherical_joint(bodyA, bodyB, ax, ay, az, opts) end

--- The rotation the spring pulls frame B toward, relative to frame A. Fed the animated pose every frame, this is what makes a ragdoll return to its animation instead of hanging limp.
---@param joint lightuserdata|table
---@param qx any
---@param qy any
---@param qz any
---@param qw any
function physics3_joint_set_target_rotation(joint, qx, qy, qz, qw) end

--- live stiffness tuning. Hertz spans the whole range from "rigid animated character that barely flinches" to "floppy ragdoll", which is why it's worth having on a key.
---@param joint lightuserdata|table
---@param hertz any
---@param damping number
function physics3_joint_set_spring(joint, hertz, damping) end

--- move a grab joint's world target (frame A on the origin-anchored world body, so local == world).
---@param joint lightuserdata|table
---@param x number
---@param y number
---@param z number
function physics3_joint_set_target(joint, x, y, z) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_destroy_joint(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function physics3_joint_is_valid(...) end

--- layer3 handle.
---@param name string
---@param w? number
---@param h? number
---@param filter? string
---@return lightuserdata
function layer3_create(name, w, h, filter) end

--- backing Layer handle (usable with all layer_* functions)
---@param l3 lightuserdata|table
---@return any
function layer3_get_layer(l3) end

--- mesh `vertices` is a flat array of floats, 8 per vertex: x,y,z, nx,ny,nz, u,v. Non-indexed triangles, so the length must be a multiple of 24. Under headless this returns 0 — a valid-looking handle that is never `alive`, so every downstream draw no-ops instead of forcing nil guards in game code.
---@param vertices number[]
---@return any
function mesh3_create(vertices) end

--- mesh All three are BINARY STRINGS, not tables: a skinned character is tens of thousands of floats and pushing them one Lua value at a time costs more than the skinning itself. Layout, per vertex: vertex_blob  8 x float32   x,y,z, nx,ny,nz, u,v   (the rest pose) index_blob   4 x uint8     bone indices weight_blob  4 x float32   weights, expected to sum to 1 Headless returns 0, matching mesh3_create: a handle that is never alive, so downstream draws no-op instead of forcing nil guards in game code.
---@param vertex_blob any
---@param index_blob any
---@param weight_blob any
---@return any
function mesh3_create_skinned(vertex_blob, index_blob, weight_blob) end

--- `matrices` is a flat table of 16*n numbers, column-major mat4 per bone, already premultiplied by the inverse rest pose. Blends the rest vertices and re-uploads. Call once per character per frame, before the layer3_mesh that draws it.
---@param mesh lightuserdata|table
---@param matrices any
function mesh3_skin(mesh, matrices) end

--- free a custom mesh id from mesh3_create_*
---@param mesh integer
function mesh3_destroy(mesh) end

--- texture is a Texture handle from texture_load (nil clears it back to the shared white texture).
---@param mesh lightuserdata|table
---@param texture lightuserdata|table
function mesh3_set_texture(mesh, texture) end

--- scroll a custom mesh's texture coordinates
---@param mesh integer
---@param u number
---@param v number
function mesh3_set_uv_offset(mesh, u, v) end

--- draw this mesh in the blended pass: depth-tested but NOT depth-written, so it's occluded by solid geometry and occludes nothing. Instances within one transparent mesh aren't sorted against each other, so build overlapping translucent surfaces back-to-front, or keep them from overlapping.
---@param mesh lightuserdata|table
---@param enabled boolean
function mesh3_set_transparent(mesh, enabled) end

--- register sparse morph targets on a skinned mesh. The blob is little-endian: u32 target_count, then per target: u32 entry_count, then per target: entry_count * (u32 corner_index, f32 dx, f32 dy, f32 dz) Positions only. Normals are left alone: a facial deformation is small enough that the shading error is invisible, and carrying delta normals would double the data for something nobody would see.
---@param mesh lightuserdata|table
---@param blob any
function mesh3_set_morphs(mesh, blob) end

--- weights is an array of one number per target. Rebuilds the morphed rest pose. Call only when the weights CHANGE; skinning re-reads the result every frame regardless.
---@param mesh lightuserdata|table
---@param weights number[]
function mesh3_morph(mesh, weights) end

--- n  (0 if the mesh isn't live)
---@param mesh lightuserdata|table
---@return any
function mesh3_vertex_count(mesh) end

--- Create new RNG instance
---@param seed integer
---@return lightuserdata
function random_create(seed) end

--- Seed the RNG
---@param seed integer
---@param rng? any
function random_seed(seed, rng) end

--- Get the current seed
---@param rng? any
---@return integer
function random_get_seed(rng) end

--- random float in [0, 1] (rng: an rng_new() stream, default the global one)
---@param rng? lightuserdata
---@return number
function random_float_01(rng) end

--- random float in [min, max]
---@param min number
---@param max number
---@param rng? lightuserdata
---@return number
function random_float(min, max, rng) end

--- random integer in [min, max] inclusive
---@param min integer
---@param max integer
---@param rng? lightuserdata
---@return integer
function random_int(min, max, rng) end

--- Random float [0, 2π]
---@param rng? any
---@return number
function random_angle(rng) end

--- Returns -1 or 1 (chance 0-100, default 50)
---@param chance? any
---@param rng? any
---@return integer
function random_sign(chance, rng) end

--- Returns true or false (chance 0-100, default 50)
---@param chance? any
---@param rng? any
---@return boolean
function random_bool(chance, rng) end

--- Gaussian distribution via Box-Muller transform
---@param mean? any
---@param stddev? any
---@param rng? any
---@return number
function random_normal(mean, stddev, rng) end

--- Pick one random element from array
---@param array any
---@param rng? any
---@return any
function random_choice(array, rng) end

--- Pick n random elements (unique indexes)
---@param array any
---@param n integer
---@param rng? any
---@return any
function random_choices(array, n, rng) end

--- Returns index (1-based) based on weights
---@param weights number[]
---@param rng? any
---@return any
function random_weighted(weights, rng) end

--- Perlin noise [-1, 1]
---@param x number
---@param y? number
---@param z? number
function noise(x, y, z) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function key_is_down(...) end

--- EDGE: went down this update. Update-only (raises from draw on desktop)
---@param key string
---@return boolean
function key_is_pressed(key) end

--- EDGE: came up this update. Update-only (raises from draw on desktop)
---@param key string
---@return boolean
function key_is_released(key) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function mouse_position(...) end

--- mouse movement since last frame in game pixels
---@return number
---@return number
function mouse_delta() end

---@param visible boolean
function mouse_set_visible(visible) end

--- relative mouse mode: hidden cursor, unbounded deltas
---@param grabbed boolean
function mouse_set_grabbed(grabbed) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function mouse_set_window_grab(...) end

--- LEVEL; 1 left, 2 right, 3 middle (LÖVE order)
---@param button integer
---@return boolean
function mouse_is_down(button) end

--- EDGE: went down this update. Update-only (raises from draw on desktop)
---@param button integer
---@return boolean
function mouse_is_pressed(button) end

--- EDGE: came up this update. Update-only (raises from draw on desktop)
---@param button integer
---@return boolean
function mouse_is_released(button) end

--- wheel x, y movement this frame
---@return integer
---@return integer
function mouse_wheel() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function input_bind(...) end

---@param name string
---@param action1__action2 any
function input_bind_chord(name, action1__action2) end

--- Table alternates: string action, number delay, string action, number delay, string action
---@param name string
---@param action1__delay1__action2__delay2__action3 any
function input_bind_sequence(name, action1__delay1__action2__delay2__action3) end

---@param name string
---@param duration number
---@param source_action any
function input_bind_hold(name, duration, source_action) end

--- seconds the named hold binding has been held (0 when not)
---@param name string
---@return number
function input_get_hold_duration(name) end

--- 'keyboard' | 'mouse' | 'gamepad': the device that produced the last input
---@return string
function input_get_last_type() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function input_start_capture(...) end

--- the control string captured since input_start_capture, or nil
---@return string|nil
function input_get_captured() end

function input_stop_capture() end

---@param action string
---@param control string
---@return boolean
function input_unbind(action, control) end

---@param action string
function input_unbind_all(action) end

--- restore the engine's default bindings
function input_bind_all() end

--- -1..1 from an action pair (gamepad axes are analog)
---@param negative string
---@param positive string
---@return number
function input_get_axis(negative, positive) end

--- normalized direction from four actions
---@param left string
---@param right string
---@param up string
---@param down string
---@return number
---@return number
function input_get_vector(left, right, up, down) end

--- 0-1, applied to gamepad axes
---@param deadzone number
function input_set_deadzone(deadzone) end

--- LEVEL: the action or chord is held
---@param name string
---@return boolean
function is_down(name) end

--- EDGE: the action or chord went down this update. Update-only (raises from draw on desktop)
---@param name string
---@return boolean
function is_pressed(name) end

--- EDGE: came up this update. Update-only (raises from draw on desktop)
---@param name string
---@return boolean
function is_released(name) end

--- any bound action pressed this update
---@return boolean
function input_any_pressed() end

--- an action pressed this update, or nil
---@return string|nil
function input_get_pressed_action() end

---@return boolean
function gamepad_is_connected() end

--- 'leftx', 'lefty', 'rightx', 'righty', 'triggerleft', 'triggerright' (0 if unknown)
---@param axis string
---@return number
function gamepad_get_axis(axis) end

--- rendered frames since boot
---@return integer
function engine_get_frame() end

--- fixed update steps since boot (120 Hz)
---@return integer
function engine_get_step() end

--- game time in seconds (sum of scaled fixed steps)
---@return number
function engine_get_time() end

--- the fixed update dt scaled by time_scale
---@return number
function engine_get_dt() end

--- the fixed update dt (1/120), unscaled
---@return number
function engine_get_unscaled_dt() end

---@return number
function engine_get_time_scale() end

--- slow-motion / speed-up multiplier on update dt
---@param scale number
function engine_set_time_scale(scale) end

--- game (backing) width in pixels
---@return integer
function engine_get_width() end

--- game (backing) height in pixels
---@return integer
function engine_get_height() end

--- window width, height in window pixels
---@return integer
---@return integer
function engine_get_window_size() end

--- window/game pixel scale (never below 1 on desktop)
---@return number
function engine_get_scale() end

---@return boolean
function engine_is_fullscreen() end

--- 'web' on the wasm build, 'windows' on every desktop build (Linux included, for now)
---@return string
function engine_get_platform() end

--- measured frames per second
---@return number
function engine_get_fps() end

--- GL draw calls issued last frame
---@return integer
function engine_get_draw_calls() end

--- table of memory / resource counters See the MEMORY TRACKING section at the top of this file for counter meanings. Physics counters come from b2World_GetCounters. Font bytes are derived from the fixed atlas size. On Windows, process_rss and process_private come from GetProcessMemoryInfo; on other platforms they read 0.
---@return any
function engine_mem_stats() end

--- high-resolution wall-clock seconds (profiling)
---@return number
function perf_time() end

--- pre-init: the game's backing resolution
---@param w integer
---@param h integer
function engine_set_game_size(w, h) end

--- window title (applies live if the window exists)
---@param title string
function engine_set_title(title) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function engine_set_cursor(...) end

--- pre-init: initial window scale over the game size
---@param scale number
function engine_set_scale(scale) end

--- applies live
---@param enabled boolean
function engine_set_vsync(enabled) end

--- applies live on desktop; pre-init it is the start state
---@param enabled boolean
function engine_set_fullscreen(enabled) end

--- the CURRENT window state, not the config flag: F11/Alt+Enter toggle at the SDL layer, so a Lua-side bool would desync.
function engine_get_fullscreen() end

--- keyboard focus right now (SDL_WINDOW_INPUT_FOCUS).
function engine_window_focused() end

--- resize the desktop window to game_size*k and recenter (the in-game 1x/2x/3x buttons). Clamped so the window fits the desktop; leaves fullscreen first if active. Returns the APPLIED scale. No-op on web (the canvas owns its size there).
---@param k number
---@return number
function engine_set_window_scale(k) end

--- live-resize the game buffer and the desktop window to w×h pixels. Without x,y keeps the current top-left (so a top-right overlay can grow downward); with x,y also moves the window (global screen coords, same frame), so a bottom-anchored overlay can grow UPWARD by passing y = anchor_bottom - h (grok-mini). Positioning needs the x11 video driver (the Linux default; Wayland ignores it). Resizes every non-fixed layer. No-op on web.
---@param w number
---@param h number
---@param x? number
---@param y? number
function engine_set_window_pixel_size(w, h, x, y) end

--- pre-init: create the window unmapped; engine_show_window() maps it (no black flash during load)
---@param hidden boolean
function engine_set_start_hidden(hidden) end

--- pre-init: request an ARGB visual so the compositor honors per-pixel alpha. Undrawn regions (the transparent clear) become see-through; lets an overlay grow by revealing content inside a fixed-size window instead of animating X resizes (which flash).
---@param bool boolean
function engine_set_alpha_window(bool) end

--- map a window created with engine_set_start_hidden
function engine_show_window() end

--- 0-255; the letterbox/exposure clear behind the composited layers. Default black; a bar-styled overlay sets its bg so resize-exposed regions never flash black.
---@param r number
---@param g any
---@param b number
function engine_set_clear_color(r, g, b) end

--- pre-init
---@param enabled boolean
function engine_set_resizable(enabled) end

--- pre-init, web only: render at the canvas's device resolution
---@param enabled boolean
function engine_set_web_native_resolution(enabled) end

--- (w, h) The logical (CSS) viewport. Desktop: == the window size (DPR is 1). Web: window.innerWidth/innerHeight (physical px = these * DPR).
---@return any
function engine_get_css_size() end

--- Device pixel ratio. Desktop: 1.0. Web: window.devicePixelRatio.
---@return number
function engine_get_dpr() end

--- accumulated touch-scroll dy since the last call (drains it)
---@return integer
function engine_get_touch_scroll() end

--- a finger landing inside this rect acts as the LEFT MOUSE BUTTON for its whole lifetime (embedded games: drag = grab, not page scroll). Call with no args to clear. Re-set it every frame the region should stay active (window px, top-left origin).
---@param x number
---@param y number
---@param w number
---@param h number
function engine_set_touch_mouse_region(x, y, w, h) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function engine_set_render_uncapped(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function engine_set_display(...) end

--- create the capture FBO and dir; every rendered frame is then saved as dir/frame_NNNNNN.png
---@param dir string
function engine_render_setup(dir) end

--- composite the current frame and save it as the next PNG in the capture dir; returns its number
---@return integer
function engine_render_save_frame() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function engine_record_start(...) end

--- push the current frame into the live ffmpeg recording pipe (engine_record_start)
function engine_record_frame() end

--- close the live ffmpeg recording pipe
function engine_record_stop() end

--- True only when a steam build found the DLL and SteamAPI_Init succeeded. Registered in EVERY build (false outside ANCHOR_STEAM) so game code never has to know which variant it runs on.
---@return boolean
function engine_steam_running() end

--- The logged-in persona name — the visible "Steam is actually talking to us" probe. nil when inactive or the persona accessor version drifted (see the module comment).
---@return string|nil
function engine_steam_name() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function engine_get_drops(...) end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function engine_get_typed_text(...) end

--- stop the main loop after this frame
function engine_quit() end

--- annotate the recording at the current frame: a note the replay viewer lists as a step. kind 'mark' (default, a game's own note), 'command', 'script' (agent tooling), 'reload'. No-op when not recording.
---@param text string
---@param kind? string
function replay_mark(text, kind) end

--- agent instances only: advance n rendered frames (2 fixed updates each) and return how many ran. A game error during a step is raised here and the instance stays alive.
---@param n? integer
---@return integer
function engine_step(n) end

--- start recording a replay now (default replays/<timestamp>.apr). Everything loaded so far and every layer are written first, so a recording started mid-run plays back complete. Raises if already recording, in playback, or on the web.
---@param path? string
---@return string
function record_start(path) end

--- string|false finalize the recording being written (atlases, mark index, trailer) and return its path; false when nothing was recording
---@return any
function record_stop() end

--- pre-init (the framework passes the init table's `record`): whether this run records from engine_init on. Without it: desktop dev runs and agent instances record; playback, headless, packaged and web runs don't.
---@param on boolean
function engine_set_record_default(on) end

--- the loop leaves the wall clock: exactly 2 fixed updates then 1 rendered frame per iteration, vsync off, recordings in synthetic 1/60 time; in playback, frames present as fast as they decode. What --render's loop did, as a switch any instance can flip (an agent instance is always fixed-step).
---@param on boolean
function engine_set_fixed_step(on) end

--- false: frames step (update, physics, input) without draw() or a render pass — a sweep that needs no picture runs at headless speed; the recorder writes empty frames meanwhile. true restores drawing.
---@param on boolean
function engine_set_draw(on) end

--- write the mix to a WAV, one video frame of audio per CAPTURED frame (arm capture with engine_render_setup). Needs an instance without an audio device: an agent instance. Raises otherwise.
---@param path string
---@return boolean
function audio_render(path) end

--- string|false finalize the WAV being written and return its path; false when none was
---@return any
function audio_render_stop() end

--- playback instances: jump to a fraction of the recording (a fast-forward; backward seeks rewind and re-run)
---@param fraction number
function replay_seek(fraction) end

--- playback instances: pause/resume (no argument toggles); returns the new state. Meaningless in an agent instance (externally paced).
---@param on? boolean
---@return boolean
function replay_pause(on) end

--- true when a human can see this instance (a shown window); false for --agent and headless
---@return boolean
function engine_visible() end

--- engine-owned facts: frame, step, time, dt, agent, visible, recording (path or false), width, height, window_w, window_h, fps
---@return table
function engine_state() end

--- composite the current frame at game resolution and write it as a PNG at path (the parent dir must exist). Unlike engine_render_setup it captures ONE frame on demand.
---@param path string
function engine_snapshot(path) end

--- queue a key press/release as if typed; the framework's update-time edges see it on the next step
---@param name string
---@param down boolean
function input_inject_key(name, down) end

--- move the mouse to a GAME-space point (letterbox-mapped to the window)
---@param x number
---@param y number
function input_inject_mouse_move(x, y) end

--- press/release mouse button 1 left, 2 right, 3 middle (LÖVE order) at the last injected position
---@param button integer
---@param down boolean
function input_inject_mouse_button(button, down) end

--- deliver typed text (up to 31 bytes per call) as SDL text input
---@param text string
function input_inject_text(text) end

--- re-run changed tracked game files (or the named one) in the globals: functions rebind, boot-made state survives, classes merge in place. Raises on a load/runtime error with the old code still running. Returns the reloaded paths.
---@param path? string
---@return string[]
function engine_reload(path) end

--- declare the one-time files (assets, layers, binds, state) that never reload; the framework passes the init table's `boot` list
---@param files string
function engine_set_boot_files(files) end

--- the reloadable files being watched, as {path = change stamp}, plus boot = {…}
---@return table
function engine_tracked_files() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function engine_init(...) end

---@return string|nil
function clipboard_get() end

---@param text string
---@return boolean
function clipboard_set(text) end

---@return boolean
function clipboard_has_text() end

--- the text pasted (Ctrl/⌘+V) into the page since the last call, or '' Web only (the browser 'paste' event fills the buffer); desktop returns '' (use clipboard_get).
---@return any
function web_paste_drain() end

--- UNDOCUMENTED (no doc comment in anchor.c yet)
---@param ... any
---@return any ...
function open_url(...) end

--- Web: background tab (see web_open_url_bg_js). Desktop: same as open_url (the OS browser decides; there's no background concept).
---@param url string
---@return boolean
function open_url_background(url) end

--- the page's URL path ('' on desktop)
---@return string
function web_location_path() end

--- pushState navigation (no-op on desktop)
---@param path string
function web_push_path(path) end

--- the path of a pending back/forward navigation, or ''
---@return string
function web_nav_pop() end

--- Reads Module.__<name>, set by the host page's boot script before the wasm starts. nil when absent or on desktop — callers gate features (analytics, later chat) on the params they need, so desktop/local-dev stay silently off.
---@param name string
---@return string|nil
function web_boot_param(name) end

--- publish a string to Module.__<name> for the host page (the reverse of web_boot_param). Desktop no-op. Used by the mobile chat DOM-input bridge.
---@param name string
---@param value number
function web_set_param(name, value) end

--- persist a string in localStorage (nil removes). web_store_get(key) -> string|nil. Web only; desktop no-ops/nil (real files there).
---@param key string
---@param value_nil any
function web_store_set(key, value_nil) end

--- localStorage read (nil on desktop)
---@param key string
---@return string|nil
function web_store_get(key) end

--- fire-and-forget POST with an optional X-Device-Token header. No return value, no callback (the response-callback machinery comes with the chat system). Desktop no-op (desktop HTTP arrives via WinHTTP later).
---@param url string
---@param body_json any
---@param token? any
function web_http_post(url, body_json, token) end

--- POST whose outcome is readable via web_http_result(id): status 200.. on completion, -1 on network error, nil while pending. For submits that must not vanish silently. Desktop no-op.
---@param id any
---@param url string
---@param body_json any
---@param token? any
function web_http_post_poll(id, url, body_json, token) end

--- kick an async GET keyed by integer id. token goes in X-Admin-Token (default) or X-Device-Token (token_is_device=true, for chat). Poll web_http_result(id) for completion. Desktop no-op.
---@param id any
---@param url string
---@param token? any
---@param token_is_device? any
function web_http_get(id, url, token, token_is_device) end

--- status, body | nil while pending (or on desktop) status -1 = network error. The response is consumed: a second call for the same id returns nil.
---@param id any
---@return any
function web_http_result(id) end

--- kick an async GET keyed by integer id. Poll http_result(id) for completion. Desktop-only; web/other no-op.
---@param id any
---@param url string
---@param token? any
---@param token_is_device? any
function http_get(id, url, token, token_is_device) end

--- kick an async POST.
---@param id integer
---@param url string
---@param body_json string
---@param token? string
---@param token_is_device? boolean
function http_post(id, url, body_json, token, token_is_device) end

--- status, body | nil while pending status 0 = transport failure (completed but no HTTP response). Consumed on read (a second call for the id -> nil).
---@param id any
---@return any
function http_result(id) end

--- flash the taskbar button until the window gains focus (FLASHW_TIMERNOFG: stops by itself if already foreground). Polite attention, no focus steal. Windows only.
function window_flash() end

--- minimize the window (SDL_MinimizeWindow). Used by tray-style apps (the chat console's start_minimized) so an autostarted tool doesn't cover the desktop.
function window_minimize() end

--- seconds since the last user input system-wide (keyboard/ mouse), via GetLastInputInfo — the same signal Windows power management uses. For presence/away logic (the chat console), idle-pause, attract modes. 0 off Windows.
---@return any
function system_idle_seconds() end

--- modifiers: 1=MOD_ALT, 2=MOD_CONTROL, 4=MOD_SHIFT, 8=MOD_WIN
---@param id any
---@param modifiers any
---@param vk_code any
---@return boolean
function hotkey_register(id, modifiers, vk_code) end

--- Windows: release a global hotkey
---@param id integer
function hotkey_unregister(id) end

--- Windows: the global hotkey fired since last frame
---@param id integer
---@return boolean
function hotkey_is_pressed(id) end

--- output_string, exit_status
---@param command any
---@return any
function os_popen(command) end

--- id | nil
---@param command any
---@return any
function process_start(command) end

--- nil | status, stdout, stderr
---@param id any
---@return any
function process_poll(id) end

--- SIGTERM the process group (posix_spawn used SETSID).
---@param id any
function process_kill(id) end

